### ISSUE TITLE
3.1 elapsed time: use a Timer ?

### ISSUE THREAD

**Issue by FObersteiner** [zigcc/zig-cookbook#31]
Since we have a [Timer](https://github.com/ziglang/zig/blob/master/lib/std/time.zig#L291) in the std lib, this might be more ergonomic:
```zig
var timer = try std.time.Timer.start();
expensive_function();
const elapsed_ns: f64 = @floatFromInt(timer.read());

print("Time elapsed in expensive_function() is: {d:.3}ms", .{
    elapsed_ns / time.ns_per_ms,
});
```
...although I think it's a good idea in principle to also introduce `Instant` in this context.

**Comment by jiacai2050** [comment]
Thanks for suggestion!

I think we can add both methods in our cookbook.
