### ISSUE TITLE
Network: UDP ?

### ISSUE THREAD

**Issue by FObersteiner** [zigcc/zig-cookbook#64]
I was wondering if it would be useful to have a UDP example? (related: #44)

I recently dug into this, and it was working out quite nicely with Zig 0.12 / 0.13-master. [Here's a gist](https://gist.github.com/FObersteiner/a5ca113b2b36c02cf456fa066f8b86d1) for an "echo" via UDP on the loopback / localhost (could also be a Unix domain socket, as an extension maybe). What the gist shows is basically sockets programming since `std.net` does not have abstractions for UDP (yet). There's no connection/handshake as in TCP, so there's no "client" or "server" in that sense.

**Comment by jiacai2050** [comment]
Thanks, UDP example looks valuable for me.  

Wait for your PR to add it.

**Comment by FObersteiner** [comment]
alright, I'll clean up the gist, so that it works similar to https://cookbook.ziglang.cc/04-01-tcp-server.html.

Officially, only Mac and Linux are supported in the cookbook examples, right? For the UDP example, it will likely work on Windows as well if you link libc (what comes with Zig on Windows). I'll need to test that tough.

**Comment by jiacai2050** [comment]
> Officially, only Mac and Linux are supported in the cookbook examples, right?

Yes, windows is a plus, not a must.
